#! /usr/local/bin/python2.7
"""
    usage: ./uploader -f uploader -d test
"""
import argparse
import os
import subprocess

import load_secrets

artifactory_url_prefix = 'artifactory_prefix'


def upload(credentials, source, target):
    _opts = [
        '-s',
        '-u "{0[username]}:{0[password]}"'.format(credentials),
        '''-H "X-Checksum-Sha1:$(sha1sum {source} | cut -d ' ' -f1 )"'''.format(source=source),
        '-T "{source}"'.format(source=source),
    ]

    cmd = 'curl {opts} "{target}"'.format(opts=' '.join(_opts), target=target)
    return subprocess.check_output(cmd, shell=True)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--file", dest='filename', required=True)
    parser.add_argument("-d", "--worker", dest='worker_name', required=True)
    args = parser.parse_args()

    secrets = load_secrets.load('artifactory')
    target = '{url_prefix}/{args.worker_name}/{file_name}'.format(
        url_prefix=artifactory_url_prefix,
        args=args,
        file_name=os.path.basename(args.filename),
    )

    print upload(credentials=secrets, source=args.filename, target=target)
