#! /usr/local/bin/python2.7
"""
    usage: ./uploader -f uploader -d test
"""
import argparse
import subprocess


parser = argparse.ArgumentParser()
parser.add_argument("-f", "--file", dest='filename', required=True)
parser.add_argument("-d", "--worker", dest='worker_name', required=True)
args = parser.parse_args()

credentials = "user:password"
archive_name = args.filename
worker_name = args.worker_name

header = "X-Checksum-Sha1:$(sha1sum %s | cut -d ' ' -f1 )" % archive_name
url = 'artifactory_prefix/%s/%s' % (worker_name, archive_name)
cmd = '''curl -s -u "%s"  -H "%s" -T "%s" "%s"''' % (credentials, header, archive_name, url)

# uncomment line below and comment second line for manual testing
# print cmd
print subprocess.check_output(cmd, shell=True)
